"""Default configuration values for AION simulation."""

DEFAULT_NUM_OSCILLATORS = 20
DEFAULT_COUPLING_STRENGTH = 2.0
DEFAULT_TIME_STEP = 0.01
DEFAULT_FREQUENCY_RANGE = (-1.0, 1.0)
DEFAULT_ANIMATION_SPEED = 1.0

